## There is a summary at the bottom of this notebook - jump to that unless you're super interested in the gory details of how these benchmarks were done, etc

In [8]:
import intake
cat = intake.cat.access_nri

cat

/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/intake/catalog/utils.py:173: UserWarning: Shell command not executed due to getshell=False
  warnings.warn("Shell command not executed due to getshell=False")
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/intake/catalog/utils.py:182: UserWarning: Shell command not executed due to getshell=False
  warnings.warn("Shell command not executed due to getshell=False")

In [9]:
from dask.distributed import Client

client = Client(threads_per_worker=1)
client

In [10]:
datastore = intake.cat.access_nri["cj877"]
datastore = datastore.search(file_id='atmos.1day.bnds:2.depth:6.lat:144.lon:192')
# dataset = datastore.to_dask()
# dataset

In [11]:
_paths = datastore.df.path.tolist()[:500]
esm_ds = datastore.search(path=_paths)
esm_ds

In [12]:
%%time
esm_ds.to_dask()

/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/intake_esm/source.py:109: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates prior reform date (1582-10-15). To silence this warning specify 'use_cftime=True'.
  ds = xr.open_dataset(url, **xarray_open_kwargs)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/intake_esm/source.py:109: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates prior reform date (1582-10-15). To silence this warning specify 'use_cftime=True'.
  ds = xr.open_dataset(url, **xarray_open_kwargs)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/intake_esm/source.py:109: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates prior reform date (1582-10-15). To silence this warning specify 'use_cftime=True'.
  ds = xr.open_dataset(url, **xarray_open_kwargs)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/intake_esm/source.py:109: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates prior reform date (1582-10-15). To silence this warning specify 'use_cftime=True'.
  ds = xr.open_dataset(url, **xarray_open_kwargs)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/intake_esm/source.py:109: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates prior reform date (1582-10-15). To silence this warning specify 'use_cftime=True'.
  ds = xr.open_dataset(url, **xarray_open_kwargs)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/intake_esm/source.py:109: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates prior reform date (1582-10-15). To silence this warning specify 'use_cftime=True'.
  ds = xr.open_dataset(url, **xarray_open_kwargs)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/intake_esm/source.py:109: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates prior reform date (1582-10-15). To silence this warning specify 'use_cftime=True'.
  ds = xr.open_dataset(url, **xarray_open_kwargs)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/intake_esm/source.py:109: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates prior reform date (1582-10-15). To silence this warning specify 'use_cftime=True'.
  ds = xr.open_dataset(url, **xarray_open_kwargs)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/intake_esm/source.py:109: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates prior reform date (1582-10-15). To silence this warning specify 'use_cftime=True'.
  ds = xr.open_dataset(url, **xarray_open_kwargs)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/intake_esm/source.py:109: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates prior reform date (1582-10-15). To silence this warning specify 'use_cftime=True'.
  ds = xr.open_dataset(url, **xarray_open_kwargs)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/intake_esm/source.py:109: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates prior reform date (1582-10-15). To silence this warning specify 'use_cftime=True'.
  ds = xr.open_dataset(url, **xarray_open_kwargs)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/intake_esm/source.py:109: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates prior reform date (1582-10-15). To silence this warning specify 'use_cftime=True'.
  ds = xr.open_dataset(url, **xarray_open_kwargs)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/intake_esm/source.py:109: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates prior reform date (1582-10-15). To silence this warning specify 'use_cftime=True'.
  ds = xr.open_dataset(url, **xarray_open_kwargs)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/intake_esm/source.py:109: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates prior reform date (1582-10-15). To silence this warning specify 'use_cftime=True'.
  ds = xr.open_dataset(url, **xarray_open_kwargs)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/intake_esm/source.py:109: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates prior reform date (1582-10-15). To silence this warning specify 'use_cftime=True'.
  ds = xr.open_dataset(url, **xarray_open_kwargs)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/intake_esm/source.py:109: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates prior reform date (1582-10-15). To silence this warning specify 'use_cftime=True'.
  ds = xr.open_dataset(url, **xarray_open_kwargs)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/intake_esm/source.py:109: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates prior reform date (1582-10-15). To silence this warning specify 'use_cftime=True'.
  ds = xr.open_dataset(url, **xarray_open_kwargs)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/intake_esm/source.py:109: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates prior reform date (1582-10-15). To silence this warning specify 'use_cftime=True'.
  ds = xr.open_dataset(url, **xarray_open_kwargs)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/intake_esm/source.py:109: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates prior reform date (1582-10-15). To silence this warning specify 'use_cftime=True'.
  ds = xr.open_dataset(url, **xarray_open_kwargs)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/intake_esm/source.py:109: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates prior reform date (1582-10-15). To silence this warning specify 'use_cftime=True'.
  ds = xr.open_dataset(url, **xarray_open_kwargs)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/intake_esm/source.py:109: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates prior reform date (1582-10-15). To silence this warning specify 'use_cftime=True'.
  ds = xr.open_dataset(url, **xarray_open_kwargs)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/intake_esm/source.py:109: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates prior reform date (1582-10-15). To silence this warning specify 'use_cftime=True'.
  ds = xr.open_dataset(url, **xarray_open_kwargs)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/intake_esm/source.py:109: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates prior reform date (1582-10-15). To silence this warning specify 'use_cftime=True'.
  ds = xr.open_dataset(url, **xarray_open_kwargs)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/intake_esm/source.py:109: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates prior reform date (1582-10-15). To silence this warning specify 'use_cftime=True'.
  ds = xr.open_dataset(url, **xarray_open_kwargs)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/intake_esm/source.py:109: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates prior reform date (1582-10-15). To silence this warning specify 'use_cftime=True'.
  ds = xr.open_dataset(url, **xarray_open_kwargs)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/intake_esm/source.py:109: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates prior reform date (1582-10-15). To silence this warning specify 'use_cftime=True'.
  ds = xr.open_dataset(url, **xarray_open_kwargs)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/intake_esm/source.py:109: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates prior reform date (1582-10-15). To silence this warning specify 'use_cftime=True'.
  ds = xr.open_dataset(url, **xarray_open_kwargs)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/intake_esm/source.py:109: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates prior reform date (1582-10-15). To silence this warning specify 'use_cftime=True'.
  ds = xr.open_dataset(url, **xarray_open_kwargs)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/intake_esm/source.py:109: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates prior reform date (1582-10-15). To silence this warning specify 'use_cftime=True'.
  ds = xr.open_dataset(url, **xarray_open_kwargs)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/intake_esm/source.py:109: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates prior reform date (1582-10-15). To silence this warning specify 'use_cftime=True'.
  ds = xr.open_dataset(url, **xarray_open_kwargs)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/intake_esm/source.py:109: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates prior reform date (1582-10-15). To silence this warning specify 'use_cftime=True'.
  ds = xr.open_dataset(url, **xarray_open_kwargs)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/intake_esm/source.py:109: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates prior reform date (1582-10-15). To silence this warning specify 'use_cftime=True'.
  ds = xr.open_dataset(url, **xarray_open_kwargs)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/intake_esm/source.py:109: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates prior reform date (1582-10-15). To silence this warning specify 'use_cftime=True'.
  ds = xr.open_dataset(url, **xarray_open_kwargs)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/intake_esm/source.py:109: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates prior reform date (1582-10-15). To silence this warning specify 'use_cftime=True'.
  ds = xr.open_dataset(url, **xarray_open_kwargs)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/intake_esm/source.py:109: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates prior reform date (1582-10-15). To silence this warning specify 'use_cftime=True'.
  ds = xr.open_dataset(url, **xarray_open_kwargs)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/intake_esm/source.py:109: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates prior reform date (1582-10-15). To silence this warning specify 'use_cftime=True'.
  ds = xr.open_dataset(url, **xarray_open_kwargs)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/intake_esm/source.py:109: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates prior reform date (1582-10-15). To silence this warning specify 'use_cftime=True'.
  ds = xr.open_dataset(url, **xarray_open_kwargs)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/intake_esm/source.py:109: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates prior reform date (1582-10-15). To silence this warning specify 'use_cftime=True'.
  ds = xr.open_dataset(url, **xarray_open_kwargs)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/intake_esm/source.py:109: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates prior reform date (1582-10-15). To silence this warning specify 'use_cftime=True'.
  ds = xr.open_dataset(url, **xarray_open_kwargs)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/intake_esm/source.py:109: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates prior reform date (1582-10-15). To silence this warning specify 'use_cftime=True'.
  ds = xr.open_dataset(url, **xarray_open_kwargs)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/intake_esm/source.py:109: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates prior reform date (1582-10-15). To silence this warning specify 'use_cftime=True'.
  ds = xr.open_dataset(url, **xarray_open_kwargs)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/intake_esm/source.py:109: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates prior reform date (1582-10-15). To silence this warning specify 'use_cftime=True'.
  ds = xr.open_dataset(url, **xarray_open_kwargs)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/intake_esm/source.py:109: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates prior reform date (1582-10-15). To silence this warning specify 'use_cftime=True'.
  ds = xr.open_dataset(url, **xarray_open_kwargs)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/intake_esm/source.py:109: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates prior reform date (1582-10-15). To silence this warning specify 'use_cftime=True'.
  ds = xr.open_dataset(url, **xarray_open_kwargs)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/intake_esm/source.py:109: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates prior reform date (1582-10-15). To silence this warning specify 'use_cftime=True'.
  ds = xr.open_dataset(url, **xarray_open_kwargs)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/intake_esm/source.py:109: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates prior reform date (1582-10-15). To silence this warning specify 'use_cftime=True'.
  ds = xr.open_dataset(url, **xarray_open_kwargs)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/intake_esm/source.py:109: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates prior reform date (1582-10-15). To silence this warning specify 'use_cftime=True'.
  ds = xr.open_dataset(url, **xarray_open_kwargs)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/intake_esm/source.py:109: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates prior reform date (1582-10-15). To silence this warning specify 'use_cftime=True'.
  ds = xr.open_dataset(url, **xarray_open_kwargs)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/intake_esm/source.py:109: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates prior reform date (1582-10-15). To silence this warning specify 'use_cftime=True'.
  ds = xr.open_dataset(url, **xarray_open_kwargs)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/intake_esm/source.py:109: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates prior reform date (1582-10-15). To silence this warning specify 'use_cftime=True'.
  ds = xr.open_dataset(url, **xarray_open_kwargs)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/intake_esm/source.py:109: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates prior reform date (1582-10-15). To silence this warning specify 'use_cftime=True'.

CPU times: user 1min 44s, sys: 34.2 s, total: 2min 18s
Wall time: 2min 37s

<xarray.Dataset> Size: 59GB
Dimensions:             (time: 15218, lat: 144, lon: 192, depth: 6, bnds: 2)
Coordinates:
  * time                (time) object 122kB 0001-01-01 12:00:00 ... 0042-08-3...
  * lat                 (lat) float64 1kB -89.38 -88.12 -86.88 ... 88.12 89.38
  * lon                 (lon) float64 2kB 0.9375 2.812 4.688 ... 357.2 359.1
  * depth               (depth) float64 48B 0.011 0.051 0.157 0.4385 1.185 3.164
    time_bnds           (time, bnds) object 243kB dask.array<chunksize=(31, 2), meta=np.ndarray>
    lat_bnds            (lat, bnds) float64 2kB dask.array<chunksize=(144, 2), meta=np.ndarray>
    lon_bnds            (lon, bnds) float64 3kB dask.array<chunksize=(192, 2), meta=np.ndarray>
    depth_bnds          (depth, bnds) float64 96B dask.array<chunksize=(6, 2), meta=np.ndarray>
    latitude_longitude  int32 4B -2147483647
    height              float64 8B 10.0
    height_0            float64 8B 1.5
Dimensions without coordinates: bnds
Data variables: (12/20)
    fld_s01i201         (time, lat, lon) float32 2GB dask.array<chunksize=(31, 144, 192), meta=np.ndarray>
    fld_s02i201         (time, lat, lon) float32 2GB dask.array<chunksize=(31, 144, 192), meta=np.ndarray>
    fld_s02i206         (time, lat, lon) float32 2GB dask.array<chunksize=(31, 144, 192), meta=np.ndarray>
    fld_s02i208         (time, lat, lon) float32 2GB dask.array<chunksize=(31, 144, 192), meta=np.ndarray>
    fld_s03i217         (time, lat, lon) float32 2GB dask.array<chunksize=(31, 144, 192), meta=np.ndarray>
    fld_s03i230         (time, lat, lon) float32 2GB dask.array<chunksize=(31, 144, 192), meta=np.ndarray>
    ...                  ...
    fld_s03i245_min     (time, lat, lon) float32 2GB dask.array<chunksize=(31, 144, 192), meta=np.ndarray>
    fld_s05i216         (time, lat, lon) float32 2GB dask.array<chunksize=(31, 144, 192), meta=np.ndarray>
    fld_s08i223         (time, depth, lat, lon) float32 10GB dask.array<chunksize=(31, 6, 144, 192), meta=np.ndarray>
    fld_s08i229         (time, depth, lat, lon) float32 10GB dask.array<chunksize=(31, 6, 144, 192), meta=np.ndarray>
    fld_s08i230         (time, depth, lat, lon) float32 10GB dask.array<chunksize=(31, 6, 144, 192), meta=np.ndarray>
    fld_s16i222         (time, lat, lon) float32 2GB dask.array<chunksize=(31, 144, 192), meta=np.ndarray>
Attributes: (12/16)
    Conventions:                              CF-1.6
    source:                                   Data from Met Office Unified Model
    um_version:                               10.6
    intake_esm_vars:                          ('fld_s01i201', 'fld_s02i201', ...
    intake_esm_attrs:file_id:                 atmos.1day.bnds:2.depth:6.lat:1...
    intake_esm_attrs:frequency:               1day
    ...                                       ...
    intake_esm_attrs:variable_units:          W m-2,W m-2,W m-2,W m-2,W m-2,m...
    intake_esm_attrs:realm:                   atmos
    intake_esm_attrs:temporal_label:          maximum,mean,minimum
    intake_esm_attrs:member:                  cj877
    intake_esm_attrs:_data_format_:           netcdf
    intake_esm_dataset_key:                   atmos.1day.bnds:2.depth:6.lat:1...

In [6]:
CONTAINER_HEADERS = {
    "X-Container-Read": ".r:*",
    "X-Container-Meta-Access-Control-Allow-Origin": "*",
    "X-Container-Meta-Access-Control-Allow-Methods": "GET, HEAD",
    "X-Container-Meta-Access-Control-Allow-Headers": "Range",
    "X-Container-Meta-Access-Control-Expose-Headers": "Accept-Ranges, Content-Length, Content-Range",
}

In [ ]:
import warnings
import os
import xarray as xr
from virtualizarr import open_virtual_dataset, open_virtual_mfdataset
from virtualizarr.parsers import HDFParser
from obstore.store import S3Store, LocalStore
from obspec_utils.registry import ObjectStoreRegistry

import numcodecs.zarr3  # Register the zarr3 codec

from pathlib import Path

from dotenv import load_dotenv
load_dotenv()

url = "s3://ct-icechunk-root/cj877-atm-icechunk"


access_key_id = os.environ.get("CJ877_ACCESS_KEY_ID")
secret_access_key = os.environ.get("CJ877_SECRET_ACCESS_KEY")

endpoint = "https://cloud.nci.org.au:8080"
bucket = "s3://ct-icechunk-root"


######################################################################################
# I think the following is irrelevant in this instance because we are virtualising
# local files. However, we'll want to put the icechunk store in this bucket, so let's 
# keep it around for now.
######################################################################################

# create s3 store with aws-style credentials
s3_store = S3Store.from_url(
    f"{bucket}",
    endpoint=endpoint,
    access_key_id=access_key_id,
    secret_access_key=secret_access_key,
)

s3_registry = ObjectStoreRegistry({f"{bucket}": s3_store})


######################################################################################


warnings.filterwarnings(
    "ignore",
    message="Numcodecs codecs are not in the Zarr version 3 specification*",
    category=UserWarning,
)

#file:///g/data/p73/archive/non-CMIP/ACCESS-CM2/cj877/history/atm/netCDF/cj877a.pd001306_dai.nc

store_root = "/g/data/p73/archive/non-CMIP/ACCESS-CM2/cj877"

store_urls = [f"file://{_path}" for _path in _paths]

store = LocalStore(prefix=store_root)
registry = ObjectStoreRegistry({f"file://{store_root}": store})

parser = HDFParser()

In [8]:
registry

In [9]:
combined_vds = open_virtual_mfdataset(
    urls=store_urls,
    parser=parser,
    registry=registry,
    combine="nested",
    concat_dim="time",
    parallel="dask",
    compat="override",
    coords=["time"],
)
combined_vds

/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/zarr/codecs/numcodecs/_codecs.py:141: ZarrUserWarning: Numcodecs codecs are not in the Zarr version 3 specification and may not be supported by other zarr implementations.
  super().__init__(**codec_config)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/zarr/codecs/numcodecs/_codecs.py:141: ZarrUserWarning: Numcodecs codecs are not in the Zarr version 3 specification and may not be supported by other zarr implementations.
  super().__init__(**codec_config)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/zarr/codecs/numcodecs/_codecs.py:141: ZarrUserWarning: Numcodecs codecs are not in the Zarr version 3 specification and may not be supported by other zarr implementations.
  super().__init__(**codec_config)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/zarr/codecs/numcodecs/_codecs.py:141: ZarrUserWarning: Numcodecs codecs are not in the Zarr version 3 specification and may not be supported by other zarr implementations.
  super().__init__(**codec_config)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/zarr/codecs/numcodecs/_codecs.py:141: ZarrUserWarning: Numcodecs codecs are not in the Zarr version 3 specification and may not be supported by other zarr implementations.
  super().__init__(**codec_config)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/zarr/codecs/numcodecs/_codecs.py:141: ZarrUserWarning: Numcodecs codecs are not in the Zarr version 3 specification and may not be supported by other zarr implementations.
  super().__init__(**codec_config)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/zarr/codecs/numcodecs/_codecs.py:141: ZarrUserWarning: Numcodecs codecs are not in the Zarr version 3 specification and may not be supported by other zarr implementations.
  super().__init__(**codec_config)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/zarr/codecs/numcodecs/_codecs.py:141: ZarrUserWarning: Numcodecs codecs are not in the Zarr version 3 specification and may not be supported by other zarr implementations.
  super().__init__(**codec_config)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/zarr/codecs/numcodecs/_codecs.py:141: ZarrUserWarning: Numcodecs codecs are not in the Zarr version 3 specification and may not be supported by other zarr implementations.
  super().__init__(**codec_config)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/zarr/codecs/numcodecs/_codecs.py:141: ZarrUserWarning: Numcodecs codecs are not in the Zarr version 3 specification and may not be supported by other zarr implementations.
  super().__init__(**codec_config)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/zarr/codecs/numcodecs/_codecs.py:141: ZarrUserWarning: Numcodecs codecs are not in the Zarr version 3 specification and may not be supported by other zarr implementations.
  super().__init__(**codec_config)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/zarr/codecs/numcodecs/_codecs.py:141: ZarrUserWarning: Numcodecs codecs are not in the Zarr version 3 specification and may not be supported by other zarr implementations.
  super().__init__(**codec_config)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/zarr/codecs/numcodecs/_codecs.py:141: ZarrUserWarning: Numcodecs codecs are not in the Zarr version 3 specification and may not be supported by other zarr implementations.
  super().__init__(**codec_config)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/zarr/codecs/numcodecs/_codecs.py:141: ZarrUserWarning: Numcodecs codecs are not in the Zarr version 3 specification and may not be supported by other zarr implementations.
  super().__init__(**codec_config)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/zarr/codecs/numcodecs/_codecs.py:141: ZarrUserWarning: Numcodecs codecs are not in the Zarr version 3 specification and may not be supported by other zarr implementations.
  super().__init__(**codec_config)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/zarr/codecs/numcodecs/_codecs.py:141: ZarrUserWarning: Numcodecs codecs are not in the Zarr version 3 specification and may not be supported by other zarr implementations.
  super().__init__(**codec_config)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/zarr/codecs/numcodecs/_codecs.py:141: ZarrUserWarning: Numcodecs codecs are not in the Zarr version 3 specification and may not be supported by other zarr implementations.
  super().__init__(**codec_config)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/zarr/codecs/numcodecs/_codecs.py:141: ZarrUserWarning: Numcodecs codecs are not in the Zarr version 3 specification and may not be supported by other zarr implementations.
  super().__init__(**codec_config)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/zarr/codecs/numcodecs/_codecs.py:141: ZarrUserWarning: Numcodecs codecs are not in the Zarr version 3 specification and may not be supported by other zarr implementations.
  super().__init__(**codec_config)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/zarr/codecs/numcodecs/_codecs.py:141: ZarrUserWarning: Numcodecs codecs are not in the Zarr version 3 specification and may not be supported by other zarr implementations.
  super().__init__(**codec_config)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/zarr/codecs/numcodecs/_codecs.py:141: ZarrUserWarning: Numcodecs codecs are not in the Zarr version 3 specification and may not be supported by other zarr implementations.
  super().__init__(**codec_config)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/zarr/codecs/numcodecs/_codecs.py:141: ZarrUserWarning: Numcodecs codecs are not in the Zarr version 3 specification and may not be supported by other zarr implementations.
  super().__init__(**codec_config)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/zarr/codecs/numcodecs/_codecs.py:141: ZarrUserWarning: Numcodecs codecs are not in the Zarr version 3 specification and may not be supported by other zarr implementations.
  super().__init__(**codec_config)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/zarr/codecs/numcodecs/_codecs.py:141: ZarrUserWarning: Numcodecs codecs are not in the Zarr version 3 specification and may not be supported by other zarr implementations.
  super().__init__(**codec_config)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/zarr/codecs/numcodecs/_codecs.py:141: ZarrUserWarning: Numcodecs codecs are not in the Zarr version 3 specification and may not be supported by other zarr implementations.
  super().__init__(**codec_config)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/zarr/codecs/numcodecs/_codecs.py:141: ZarrUserWarning: Numcodecs codecs are not in the Zarr version 3 specification and may not be supported by other zarr implementations.
  super().__init__(**codec_config)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/zarr/codecs/numcodecs/_codecs.py:141: ZarrUserWarning: Numcodecs codecs are not in the Zarr version 3 specification and may not be supported by other zarr implementations.
  super().__init__(**codec_config)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/zarr/codecs/numcodecs/_codecs.py:141: ZarrUserWarning: Numcodecs codecs are not in the Zarr version 3 specification and may not be supported by other zarr implementations.
  super().__init__(**codec_config)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/zarr/codecs/numcodecs/_codecs.py:141: ZarrUserWarning: Numcodecs codecs are not in the Zarr version 3 specification and may not be supported by other zarr implementations.
  super().__init__(**codec_config)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/zarr/codecs/numcodecs/_codecs.py:141: ZarrUserWarning: Numcodecs codecs are not in the Zarr version 3 specification and may not be supported by other zarr implementations.
  super().__init__(**codec_config)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/zarr/codecs/numcodecs/_codecs.py:141: ZarrUserWarning: Numcodecs codecs are not in the Zarr version 3 specification and may not be supported by other zarr implementations.
  super().__init__(**codec_config)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/zarr/codecs/numcodecs/_codecs.py:141: ZarrUserWarning: Numcodecs codecs are not in the Zarr version 3 specification and may not be supported by other zarr implementations.
  super().__init__(**codec_config)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/zarr/codecs/numcodecs/_codecs.py:141: ZarrUserWarning: Numcodecs codecs are not in the Zarr version 3 specification and may not be supported by other zarr implementations.
  super().__init__(**codec_config)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/zarr/codecs/numcodecs/_codecs.py:141: ZarrUserWarning: Numcodecs codecs are not in the Zarr version 3 specification and may not be supported by other zarr implementations.
  super().__init__(**codec_config)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/zarr/codecs/numcodecs/_codecs.py:141: ZarrUserWarning: Numcodecs codecs are not in the Zarr version 3 specification and may not be supported by other zarr implementations.
  super().__init__(**codec_config)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/zarr/codecs/numcodecs/_codecs.py:141: ZarrUserWarning: Numcodecs codecs are not in the Zarr version 3 specification and may not be supported by other zarr implementations.
  super().__init__(**codec_config)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/zarr/codecs/numcodecs/_codecs.py:141: ZarrUserWarning: Numcodecs codecs are not in the Zarr version 3 specification and may not be supported by other zarr implementations.
  super().__init__(**codec_config)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/zarr/codecs/numcodecs/_codecs.py:141: ZarrUserWarning: Numcodecs codecs are not in the Zarr version 3 specification and may not be supported by other zarr implementations.
  super().__init__(**codec_config)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/virtualizarr/xarray.py:479: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates prior reform date (1582-10-15). To silence this warning specify 'use_cftime=True'.
  with xr.open_zarr(
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/zarr/codecs/numcodecs/_codecs.py:141: ZarrUserWarning: Numcodecs codecs are not in the Zarr version 3 specification and may not be supported by other zarr implementations.
  super().__init__(**codec_config)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/virtualizarr/xarray.py:479: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates prior reform date (1582-10-15). To silence this warning specify 'use_cftime=True'.
  with xr.open_zarr(
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/zarr/codecs/numcodecs/_codecs.py:141: ZarrUserWarning: Numcodecs codecs are not in the Zarr version 3 specification and may not be supported by other zarr implementations.
  super().__init__(**codec_config)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/zarr/codecs/numcodecs/_codecs.py:141: ZarrUserWarning: Numcodecs codecs are not in the Zarr version 3 specification and may not be supported by other zarr implementations.
  super().__init__(**codec_config)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/virtualizarr/xarray.py:479: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates prior reform date (1582-10-15). To silence this warning specify 'use_cftime=True'.
  with xr.open_zarr(
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/virtualizarr/xarray.py:479: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates prior reform date (1582-10-15). To silence this warning specify 'use_cftime=True'.
  with xr.open_zarr(
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/virtualizarr/xarray.py:479: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates prior reform date (1582-10-15). To silence this warning specify 'use_cftime=True'.
  with xr.open_zarr(
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/zarr/codecs/numcodecs/_codecs.py:141: ZarrUserWarning: Numcodecs codecs are not in the Zarr version 3 specification and may not be supported by other zarr implementations.
  super().__init__(**codec_config)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/zarr/codecs/numcodecs/_codecs.py:141: ZarrUserWarning: Numcodecs codecs are not in the Zarr version 3 specification and may not be supported by other zarr implementations.
  super().__init__(**codec_config)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/zarr/codecs/numcodecs/_codecs.py:141: ZarrUserWarning: Numcodecs codecs are not in the Zarr version 3 specification and may not be supported by other zarr implementations.
  super().__init__(**codec_config)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/virtualizarr/xarray.py:479: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates prior reform date (1582-10-15). To silence this warning specify 'use_cftime=True'.
  with xr.open_zarr(
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/zarr/codecs/numcodecs/_codecs.py:141: ZarrUserWarning: Numcodecs codecs are not in the Zarr version 3 specification and may not be supported by other zarr implementations.
  super().__init__(**codec_config)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/zarr/codecs/numcodecs/_codecs.py:141: ZarrUserWarning: Numcodecs codecs are not in the Zarr version 3 specification and may not be supported by other zarr implementations.
  super().__init__(**codec_config)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/virtualizarr/xarray.py:479: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates prior reform date (1582-10-15). To silence this warning specify 'use_cftime=True'.
  with xr.open_zarr(
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/virtualizarr/xarray.py:479: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates prior reform date (1582-10-15). To silence this warning specify 'use_cftime=True'.
  with xr.open_zarr(
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/virtualizarr/xarray.py:479: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates prior reform date (1582-10-15). To silence this warning specify 'use_cftime=True'.
  with xr.open_zarr(
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/virtualizarr/xarray.py:479: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates prior reform date (1582-10-15). To silence this warning specify 'use_cftime=True'.
  with xr.open_zarr(
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/zarr/codecs/numcodecs/_codecs.py:141: ZarrUserWarning: Numcodecs codecs are not in the Zarr version 3 specification and may not be supported by other zarr implementations.
  super().__init__(**codec_config)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/zarr/codecs/numcodecs/_codecs.py:141: ZarrUserWarning: Numcodecs codecs are not in the Zarr version 3 specification and may not be supported by other zarr implementations.
  super().__init__(**codec_config)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/virtualizarr/xarray.py:479: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates prior reform date (1582-10-15). To silence this warning specify 'use_cftime=True'.
  with xr.open_zarr(
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/virtualizarr/xarray.py:479: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates prior reform date (1582-10-15). To silence this warning specify 'use_cftime=True'.
  with xr.open_zarr(
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/virtualizarr/xarray.py:479: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates prior reform date (1582-10-15). To silence this warning specify 'use_cftime=True'.
  with xr.open_zarr(
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/virtualizarr/xarray.py:479: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates prior reform date (1582-10-15). To silence this warning specify 'use_cftime=True'.
  with xr.open_zarr(
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/zarr/codecs/numcodecs/_codecs.py:141: ZarrUserWarning: Numcodecs codecs are not in the Zarr version 3 specification and may not be supported by other zarr implementations.
  super().__init__(**codec_config)
/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/virtualizarr/xarray.py:479: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates prior reform date (1582-10-15). To silence this warning specify 'use_cftime=True'.
  with xr.open_zarr(

<xarray.Dataset> Size: 59GB
Dimensions:             (time: 15218, lat: 144, lon: 192, bnds: 2, depth: 6)
Coordinates:
  * time                (time) object 122kB 0001-01-01 12:00:00 ... 0042-08-3...
  * lat                 (lat) float64 1kB -89.38 -88.12 -86.88 ... 88.12 89.38
  * lon                 (lon) float64 2kB 0.9375 2.812 4.688 ... 357.2 359.1
  * depth               (depth) float64 48B 0.011 0.051 0.157 0.4385 1.185 3.164
    height              float64 8B ManifestArray<shape=(), dtype=float64, chu...
    height_0            float64 8B ManifestArray<shape=(), dtype=float64, chu...
Dimensions without coordinates: bnds
Data variables: (12/25)
    fld_s01i201         (time, lat, lon) float32 2GB ManifestArray<shape=(152...
    latitude_longitude  (time) int32 61kB ManifestArray<shape=(15218,), dtype...
    time_bnds           (time, bnds) float64 243kB ManifestArray<shape=(15218...
    lat_bnds            (time, lat, bnds) float64 35MB ManifestArray<shape=(1...
    lon_bnds            (time, lon, bnds) float64 47MB ManifestArray<shape=(1...
    fld_s02i201         (time, lat, lon) float32 2GB ManifestArray<shape=(152...
    ...                  ...
    fld_s05i216         (time, lat, lon) float32 2GB ManifestArray<shape=(152...
    fld_s08i223         (time, depth, lat, lon) float32 10GB ManifestArray<sh...
    depth_bnds          (time, depth, bnds) float64 1MB ManifestArray<shape=(...
    fld_s08i229         (time, depth, lat, lon) float32 10GB ManifestArray<sh...
    fld_s08i230         (time, depth, lat, lon) float32 10GB ManifestArray<sh...
    fld_s16i222         (time, lat, lon) float32 2GB ManifestArray<shape=(152...
Attributes:
    history:      File /jobfs/32039470.gadi-pbs/cj877a.pd0001jan converted wi...
    Conventions:  CF-1.6
    source:       Data from Met Office Unified Model
    um_version:   10.6

In [10]:
# And write to a local kerchunk container using json
combined_vds.vz.to_kerchunk(
    filepath="/home/189/ct1163/cj877-atm.json",
    format='json',
)

# This is fine, but it's really not very interesting. What we'd like to do is write
# it straight into the object store.

# In the cell below, I'm just opening that same reference - manually copied
# into the nirin object store. It's honestly a lot slower than I'd like from an 
# ARE session, so probably not really workable as a virtualisation solution right
# now, unless we can figure out why the hell it's so slow.

# Also, this is using the swift protocol. I don't know if s3 is going to be faster

In [7]:
%%time
import xarray as xr
url = "https://cloud.nci.org.au:8080/swift/v1/AUTH_de20573c22894dda9a98b247bd936171/ct-icechunk-root/cj877-atm.json"
ds = xr.open_dataset(
    "reference://", engine="zarr",
    backend_kwargs={
        "storage_options": {
            "fo": url,
        },
        "consolidated": False
    }, 
)
ds

CPU times: user 1.51 s, sys: 339 ms, total: 1.85 s
Wall time: 43 s

<timed exec>:3: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates prior reform date (1582-10-15). To silence this warning specify 'use_cftime=True'.

<xarray.Dataset> Size: 59GB
Dimensions:             (time: 15218, lat: 144, lon: 192, bnds: 2, depth: 6)
Coordinates:
  * time                (time) object 122kB 0001-01-01 12:00:00 ... 0042-08-3...
  * lat                 (lat) float64 1kB -89.38 -88.12 -86.88 ... 88.12 89.38
  * lon                 (lon) float64 2kB 0.9375 2.812 4.688 ... 357.2 359.1
  * depth               (depth) float64 48B 0.011 0.051 0.157 0.4385 1.185 3.164
    height              float64 8B ...
    height_0            float64 8B ...
Dimensions without coordinates: bnds
Data variables: (12/25)
    fld_s01i201         (time, lat, lon) float32 2GB ...
    latitude_longitude  (time) float64 122kB ...
    time_bnds           (time, bnds) object 243kB ...
    lat_bnds            (time, lat, bnds) float64 35MB ...
    lon_bnds            (time, lon, bnds) float64 47MB ...
    fld_s02i201         (time, lat, lon) float32 2GB ...
    ...                  ...
    fld_s05i216         (time, lat, lon) float32 2GB ...
    fld_s08i223         (time, depth, lat, lon) float32 10GB ...
    depth_bnds          (time, depth, bnds) float64 1MB ...
    fld_s08i229         (time, depth, lat, lon) float32 10GB ...
    fld_s08i230         (time, depth, lat, lon) float32 10GB ...
    fld_s16i222         (time, lat, lon) float32 2GB ...
Attributes:
    history:      File /jobfs/32039470.gadi-pbs/cj877a.pd0001jan converted wi...
    Conventions:  CF-1.6
    source:       Data from Met Office Unified Model
    um_version:   10.6

In [ ]:
url = "s3://ct-icechunk-root/cj877-atm.json"

# This is a bit of a mouthful...
ds = xr.open_dataset(
    "reference://", engine="zarr",
    backend_kwargs={
        "storage_options": {
            "fo": url,
            "remote_protocol": "s3",
            "remote_options": {
                "asynchronous": True, 
                "endpoint_url": "https://cloud.nci.org.au:8080",
                "access_key_id": access_key_id,
                "secret_access_key" : secret_access_key,
            },
        },
        "consolidated": False
    }, 
)
ds

### Okay, now we've tried letting everything read that kerchunk file (hopeless for this use case! 🙁), let's instead try using icechunk.

In [12]:
import icechunk
import tempfile
from pathlib import Path
storage = icechunk.local_filesystem_storage(
    path= str(Path("~/cj877-atm-icechunk").expanduser())
)

store = icechunk.local_filesystem_store(
    str(Path("~/cj877-atm-icechunk").expanduser())
)


# repo = icechunk.Repository.create(storage)

# session = repo.writable_session("main")

##
config = icechunk.RepositoryConfig.default()
config.set_virtual_chunk_container(
    icechunk.VirtualChunkContainer(
        url_prefix=f"file://{store_root}/",
        store = store
    )
)

repo = icechunk.Repository.create(
    storage,
    config,
)

session = repo.writable_session("main")

combined_vds.vz.to_icechunk(session.store)

session.commit("Wrote to virtual icechunk store!")

  2026-03-26T06:46:15.857934Z  WARN icechunk::storage::object_store: The LocalFileSystem storage is not safe for concurrent commits. If more than one thread/process will attempt to commit at the same time, prefer using object stores.
    at icechunk/src/storage/object_store.rs:92

IcechunkError:   x repositories can only be created in clean prefixes
  |
  | context:
  |    0: icechunk::repository::create
  |              at icechunk/src/repository.rs:176
  |
  `-> repositories can only be created in clean prefixes

In [ ]:
store_root

In [ ]:
# Need to re-open the repo with the same virtual chunk authorization to read data
virtual_chunk_store = icechunk.local_filesystem_store(store_root)
config_ro = icechunk.RepositoryConfig.default()
config_ro.set_virtual_chunk_container(
    icechunk.VirtualChunkContainer(
        url_prefix=f"file://{store_root}/",
        store=virtual_chunk_store,
    )
)

repo_ro = icechunk.Repository.open(storage, config=config_ro)
session_ro = repo_ro.readonly_session("main")
xr.open_zarr(session_ro.store, consolidated=False)

In [13]:
# Claudes bugfixes
import icechunk
from pathlib import Path

storage = icechunk.local_filesystem_storage(
    path=str(Path("~/cj877-atm-icechunk").expanduser())
)

config = icechunk.RepositoryConfig.default()
config.set_virtual_chunk_container(
    icechunk.VirtualChunkContainer(
        f"file://{store_root}/",
        icechunk.local_filesystem_store(store_root),
    )
)

# Must explicitly authorize the container (icechunk is safe-by-default and
# won't read virtual chunks unless the caller opts in). None = no credentials
# needed for local filesystem, but you still must pass it.
credentials = icechunk.containers_credentials({
    f"file://{store_root}/": None,
})

repo = icechunk.Repository.create(storage, config, credentials)

session = repo.writable_session("main")

combined_vds.vz.to_icechunk(session.store)

session.commit("Wrote to virtual icechunk store!")

  2026-03-26T06:46:35.525482Z  WARN icechunk::storage::object_store: The LocalFileSystem storage is not safe for concurrent commits. If more than one thread/process will attempt to commit at the same time, prefer using object stores.
    at icechunk/src/storage/object_store.rs:92

'D81TABGFF14B1CTRV200'

In [15]:
f"file://{store_root}/"

'file:///g/data/p73/archive/non-CMIP/ACCESS-CM2/cj877/'

In [6]:
%%timeit 
import xarray as xr
import icechunk
from dotenv import load_dotenv

import os
url = "s3://ct-icechunk-root/cj877-atm-icechunk"
load_dotenv()

access_key_id = os.environ.get("CJ877_ACCESS_KEY_ID")
secret_access_key = os.environ.get("CJ877_SECRET_ACCESS_KEY")

storage = icechunk.s3_storage(
    endpoint_url="https://cloud.nci.org.au:8080",
    bucket="ct-icechunk-root",
    prefix="cj877-atm-icechunk",
    force_path_style=True,
    access_key_id = access_key_id,
    secret_access_key =secret_access_key,
    # anonymous=True,
)

credentials = icechunk.containers_credentials({
    'file:///g/data/p73/archive/non-CMIP/ACCESS-CM2/cj877/': None,
})


repo = icechunk.Repository.open(storage, authorize_virtual_chunk_access=credentials)


session = repo.readonly_session("main")

xr.open_zarr(session.store, consolidated=False, decode_times=False, decode_cf=False, decode_coords=False, decode_timedelta=False)

# Takes 1.45 s ± 60.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

  2026-03-26T23:49:47.784193Z  WARN aws_config::imds::region: failed to load region from IMDS, err: failed to load IMDS session token: dispatch failure: timeout: client error (Connect): HTTP connect timeout occurred after 1s: timed out (FailedToLoadToken(FailedToLoadToken { source: DispatchFailure(DispatchFailure { source: ConnectorError { kind: Timeout, source: hyper_util::client::legacy::Error(Connect, HttpTimeoutError { kind: "HTTP connect", duration: 1s }), connection: Unknown } }) }))
    at /home/conda/feedstock_root/build_artifacts/icechunk_1773674386695/_build_env/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/aws-config-1.8.12/src/imds/region.rs:66

/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/zarr/codecs/numcodecs/_codecs.py:141: ZarrUserWarning: Numcodecs codecs are not in the Zarr version 3 specification and may not be supported by other zarr implementations.
  super().__init__(**codec_config)

  2026-03-26T23:49:49.204217Z  WARN aws_config::imds::region: failed to load region from IMDS, err: failed to load IMDS session token: dispatch failure: timeout: client error (Connect): HTTP connect timeout occurred after 1s: timed out (FailedToLoadToken(FailedToLoadToken { source: DispatchFailure(DispatchFailure { source: ConnectorError { kind: Timeout, source: hyper_util::client::legacy::Error(Connect, HttpTimeoutError { kind: "HTTP connect", duration: 1s }), connection: Unknown } }) }))
    at /home/conda/feedstock_root/build_artifacts/icechunk_1773674386695/_build_env/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/aws-config-1.8.12/src/imds/region.rs:66

/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/zarr/codecs/numcodecs/_codecs.py:141: ZarrUserWarning: Numcodecs codecs are not in the Zarr version 3 specification and may not be supported by other zarr implementations.
  super().__init__(**codec_config)

  2026-03-26T23:49:50.579018Z  WARN aws_config::imds::region: failed to load region from IMDS, err: failed to load IMDS session token: dispatch failure: timeout: client error (Connect): HTTP connect timeout occurred after 1s: timed out (FailedToLoadToken(FailedToLoadToken { source: DispatchFailure(DispatchFailure { source: ConnectorError { kind: Timeout, source: hyper_util::client::legacy::Error(Connect, HttpTimeoutError { kind: "HTTP connect", duration: 1s }), connection: Unknown } }) }))
    at /home/conda/feedstock_root/build_artifacts/icechunk_1773674386695/_build_env/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/aws-config-1.8.12/src/imds/region.rs:66

/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/zarr/codecs/numcodecs/_codecs.py:141: ZarrUserWarning: Numcodecs codecs are not in the Zarr version 3 specification and may not be supported by other zarr implementations.
  super().__init__(**codec_config)

  2026-03-26T23:49:52.022680Z  WARN aws_config::imds::region: failed to load region from IMDS, err: failed to load IMDS session token: dispatch failure: timeout: client error (Connect): HTTP connect timeout occurred after 1s: timed out (FailedToLoadToken(FailedToLoadToken { source: DispatchFailure(DispatchFailure { source: ConnectorError { kind: Timeout, source: hyper_util::client::legacy::Error(Connect, HttpTimeoutError { kind: "HTTP connect", duration: 1s }), connection: Unknown } }) }))
    at /home/conda/feedstock_root/build_artifacts/icechunk_1773674386695/_build_env/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/aws-config-1.8.12/src/imds/region.rs:66

/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/zarr/codecs/numcodecs/_codecs.py:141: ZarrUserWarning: Numcodecs codecs are not in the Zarr version 3 specification and may not be supported by other zarr implementations.
  super().__init__(**codec_config)

  2026-03-26T23:49:53.421527Z  WARN aws_config::imds::region: failed to load region from IMDS, err: failed to load IMDS session token: dispatch failure: timeout: client error (Connect): HTTP connect timeout occurred after 1s: timed out (FailedToLoadToken(FailedToLoadToken { source: DispatchFailure(DispatchFailure { source: ConnectorError { kind: Timeout, source: hyper_util::client::legacy::Error(Connect, HttpTimeoutError { kind: "HTTP connect", duration: 1s }), connection: Unknown } }) }))
    at /home/conda/feedstock_root/build_artifacts/icechunk_1773674386695/_build_env/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/aws-config-1.8.12/src/imds/region.rs:66

/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/zarr/codecs/numcodecs/_codecs.py:141: ZarrUserWarning: Numcodecs codecs are not in the Zarr version 3 specification and may not be supported by other zarr implementations.
  super().__init__(**codec_config)

  2026-03-26T23:49:54.802044Z  WARN aws_config::imds::region: failed to load region from IMDS, err: failed to load IMDS session token: dispatch failure: timeout: client error (Connect): HTTP connect timeout occurred after 1s: timed out (FailedToLoadToken(FailedToLoadToken { source: DispatchFailure(DispatchFailure { source: ConnectorError { kind: Timeout, source: hyper_util::client::legacy::Error(Connect, HttpTimeoutError { kind: "HTTP connect", duration: 1s }), connection: Unknown } }) }))
    at /home/conda/feedstock_root/build_artifacts/icechunk_1773674386695/_build_env/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/aws-config-1.8.12/src/imds/region.rs:66

/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/zarr/codecs/numcodecs/_codecs.py:141: ZarrUserWarning: Numcodecs codecs are not in the Zarr version 3 specification and may not be supported by other zarr implementations.
  super().__init__(**codec_config)

  2026-03-26T23:49:56.172110Z  WARN aws_config::imds::region: failed to load region from IMDS, err: failed to load IMDS session token: dispatch failure: timeout: client error (Connect): HTTP connect timeout occurred after 1s: timed out (FailedToLoadToken(FailedToLoadToken { source: DispatchFailure(DispatchFailure { source: ConnectorError { kind: Timeout, source: hyper_util::client::legacy::Error(Connect, HttpTimeoutError { kind: "HTTP connect", duration: 1s }), connection: Unknown } }) }))
    at /home/conda/feedstock_root/build_artifacts/icechunk_1773674386695/_build_env/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/aws-config-1.8.12/src/imds/region.rs:66

/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/zarr/codecs/numcodecs/_codecs.py:141: ZarrUserWarning: Numcodecs codecs are not in the Zarr version 3 specification and may not be supported by other zarr implementations.
  super().__init__(**codec_config)

  2026-03-26T23:49:57.519840Z  WARN aws_config::imds::region: failed to load region from IMDS, err: failed to load IMDS session token: dispatch failure: timeout: client error (Connect): HTTP connect timeout occurred after 1s: timed out (FailedToLoadToken(FailedToLoadToken { source: DispatchFailure(DispatchFailure { source: ConnectorError { kind: Timeout, source: hyper_util::client::legacy::Error(Connect, HttpTimeoutError { kind: "HTTP connect", duration: 1s }), connection: Unknown } }) }))
    at /home/conda/feedstock_root/build_artifacts/icechunk_1773674386695/_build_env/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/aws-config-1.8.12/src/imds/region.rs:66

/g/data/xp65/public/apps/med_conda/envs/analysis3-26.03/lib/python3.12/site-packages/zarr/codecs/numcodecs/_codecs.py:141: ZarrUserWarning: Numcodecs codecs are not in the Zarr version 3 specification and may not be supported by other zarr implementations.
  super().__init__(**codec_config)

1.38 s ± 26.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

# Summary
---

<table>
  <thead>
    <tr>
      <th rowspan="2">Format</th>
      <th colspan="4" style="text-align:center">On Gadi</th>
      <th colspan="4" style="text-align:center">Remote</th>
    </tr>
    <tr>
      <th>Possible?</th>
      <th>Without credentials?</th>
      <th>Open time</th>
      <th>Dask cluster?</th>
      <th>Possible?</th>
      <th>Without credentials?</th>
      <th>Open time</th>
      <th>Dask cluster?</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Raw NetCDF</td>
      <td>✅</td><td>✅</td><td style="background-color:#f4cccc">2m 37s</td><td>48 workers</td>
      <td>❌</td><td>❌</td><td style="background-color:#b7b7b7">N/A</td><td>N/A</td>
    </tr>
    <tr>
      <td>Kerchunk</td>
      <td>✅</td><td>✅</td><td style="background-color:#fff2cc">45s</td><td>None</td>
      <td>✅</td><td>✅</td><td style="background-color:#d9ead3">2.6s</td><td>None</td>
    </tr>
    <tr>
      <td>Icechunk</td>
      <td>✅</td><td>✅¹</td><td style="background-color:#d9ead3">1.45s</td><td>None</td>
      <td>✅</td><td>❌ ²</td><td style="background-color:#d9ead3">2.2s²</td><td>None</td>
    </tr>
  </tbody>
</table>

¹ This is with the icechunk repo serialised onto the local filesystem. We wouldn't really want to do this...

² Icechunk remote requires credentials on NCI Nirin — the S3 gateway does not support anonymous access. Open time shown is with credentials.

---

Notes: 
- Kerchunk remote read occurs via Swift. Why is performance so much worse via ARE than remotely? This would be worth understanding.
- Icechunk does not have Swift support (AFAIK, will investigate further).
- Virtualisation is *always faster* than opening the raw files, although this would probably decrease when we move to smaller datasets (fewer files).
- Updating the catalog to work with icechunk would be a fair amount more work than updating to kerchunk, as we'll need to add the capabilities to intake-esm. However, this should probably be a long term goal for that library anyway.
- Updating to icechunk also lets us do some clever stuff with the catalog, in particular around checking that datastores are up to date (https://virtualizarr.readthedocs.io/en/stable/api/serialization.html#virtualizarr.accessor.VirtualiZarrDataTreeAccessor.to_icechunk). This would allow for more frequent rebuilds (ie. nightly).


---
# What we would like to do

- Support for rectilinear chunk grids is coming to [icechunk](https://github.com/earth-mover/icechunk/issues/1338#event-23657319028) and more generally [zarr](https://github.com/zarr-developers/zarr-python/pull/3534).
- This will unblock total virtualisation of the catalog, which will:
  1. Make opening any datasets in the catalog way quicker.
  2. Totally decouple the metadata and the data itself. The remote reads of icechunk & the kerchunk datastores are this: try to load the data itself (on gdata) and it fails. Implications:
        - Discoverability no longer requires being on Gadi, we can ship xarray data reprs to the interactive catalog (missing & very useful capability). See [Pangeo Catalog example](https://catalog.pangeo.io/browse/master/atmosphere/sam_ngaqua_qobs_eqx_3d/).
        - Way better performance - both due to less files being touched (lustre), cached concatenation (this *is* what virtualisation is).
- I personally think it's crucial that we try to keep as close to a single source of truth as possible with this. Currently we have two mirrors of the same catalog - `/g/data/xp65/` (`intake.cat.access_nri`) and in Nectar (interactive data catalogue). This is not really optimal since it's possible for them to get out of sync. If possible, the 'best' solution would be to move the interactive data catalog to Nirin, provided we can access it from the compute nodes (presently or request it from NCI). We then get rid of the `/g/data/xp65` version and/or use it as a build step, so we have a single catalog.
- The potential for this sort of issue/chicanery gets multiplied the more of this duplicate infra we have. Right now, we could
  1. Virtualise a dataset
  2. Serialise as kerchunk & as icechunk
  3. Read kerchunk remotely for interactive data catalogue and icechunk locally for `intake.cat.access_nri`.
- The number of datasets >> the number of catalogue files, so the potential for things to get out of sync is much higher. This will basically break our discovery/hand-holding pipeline, which is a really bad look for a toolchain designed to make life easier.
- So realistically, we need a single set of virtualised indices which both toolchains read.
---

# Blockers for Kerchunk

- Shocking performance on Gadi would need fixing.
- Rectilinear chunk grids are yet to be implemented in Zarr-Python, and I think Martin will need to wait for that before he can do the kerchunk implementation.

# Blockers for icechunk
- s3 credentials required. This could be worked around by having the interactive catalogue contain them, but that's far from secure.
- We could also have the interactive catalogue fetch the xarray repr's from a server running in Nirin which has access to credentials. This might be simpler.
- If we don't have anonymous s3 access, we'd also need to store credentials either in the xp65 conda environment or somewhere in the ACCESS-NRI Intake Catalog Package. Again, we do similar things already, but I think we should seriously consider making anonymous s3 access actually work, as it's simpler.
- We need to integrate it with intake-esm. This might not be too hard for a 'just fetch me the head' of `main` workflow. 
- 2.0 Release. Rectilinear chunk grids are implemented, we just need the feature to be released.

# Blockers for both
- Having a single source of truth for virtualised datasets requires being able to talk to the Nirin object storage from compute nodes, at the very least. There may be other complexities I'm not aware of.

___
# Cliff Notes
Most likely optimal strategy:
- Virtualise with icechunk, write virtual icechunk stores into Nirin Object storage.
- Have a server running in Nirin which serves the xarray reprs for these datasets by reading from the buckets sitting next to it for interactive catalogue.
- The catalog on Gadi just reads virtual datasets out of these buckets.
- Ideally, we move the catalog itself (parquet files) into one of these buckets too.
- Requires some care to ensure we don't mess everything up on a compute node. I think Andrew said there are precedents which might allow us to do this.